// LOCALHOST
### Get all read books
GET http://localhost:8080/read

### Add a read book
POST http://localhost:8080/read
Content-Type: application/json

{
    "title": "Harry Potter and the Goblet of Fire",
    "author": "J.K. Rowling",
    "rating": 4.5,
    "review": "Great book! Loved all the action that took place. Harry VS Dragon was so much fun to read.",
    "date_finished": "Nov 13, 2006"
}