// LOCALHOST
### Get all read books
GET http://localhost:8080/read

### Add a read book
POST http://localhost:8080/read
Content-Type: application/json

{
    "title": "Enders Game",
    "author": "Orson Scott Card",
    "rating": 4.5,
    "review": "One of my all time favorites. Fantastic story. One of the best Sci-Fi books out there.",
    "date_started": "Nov 30, 2006",
    "date_finished": "Dec 12, 2006",
    "would_reread": true
}

### Add a read book with invalid input
POST http://localhost:8080/read
Content-Type: application/json

{
    "title": "Enders Game",
    "author": "Orson Scott Card",
    "rating": 10.5,
    "review": "One of my all time favorites. Fantastic story. One of the best Sci-Fi books out there.",
    "date_started": "Nov 20, 2006",
    "date_finished": "Dec 12, 2006",
    "would_reread": true
}

### Update a read book with ID
PUT http://localhost:8080/read/67005c05f3584794af2d1c43
Content-Type: application/json

{
    "title": "Enders Game",
    "author": "Orson Scott Card",
    "rating": 3.5,
    "review": "One of my all time favorites. Fantastic story. One of the best Sci-Fi books out there.",
    "date_started": "Dec 1, 2021",
    "date_finished": "Dec 12, 1111",
    "would_reread": true
}

### Update a read book with invalid ID
PUT http://localhost:8080/read/67005fd3488413322363401
Content-Type: application/json

{
    "title": "Enders Game",
    "author": "Orson Scott Card",
    "rating": 3.5,
    "review": "One of my all time favorites. Fantastic story. One of the best Sci-Fi books out there.",
    "date_started": "Nov 1, 2000",
    "date_finished": "Dec 12, 0000",
    "would_reread": true
}

### Update a read book with ID invalid Data
PUT http://localhost:8080/read/67005c05f3584794af2d1c43
Content-Type: application/json

{
    "title": "Enders Game",
    "author": "Orson Scott Card",
    "rating": 10.5,
    "review": "One of my all time favorites. Fantastic story. One of the best Sci-Fi books out there.",
    "date_started": "Nov 1, 2021",
    "date_finished": "Dec 12, 1111",
    "would_reread": true
}

### Delete a read book by ID
DELETE http://localhost:8080/read/67005c05f3584794af2d1c43

### Delete a read book by ID -- Invalid ID
DELETE http://localhost:8080/read/67005c05f3584794af2d1c41
